#!/usr/bin/env bash
# Auto-generated e2e test for gpt-4o
# Generated by scripts/generate_model_tests.py from models/registry.yaml
# DO NOT EDIT — regenerate with: python scripts/generate_model_tests.py

set -euo pipefail

TESTS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
source "$TESTS_DIR/_stories_helpers.sh"
PYTHON_BIN="${PYTHON_BIN:-$(ruleshield_python_bin)}"

MODEL="gpt-4o"
PROXY_URL="${RULESHIELD_PROXY_URL:-http://127.0.0.1:8347}"

echo "=== E2E: GPT-4o ($MODEL) ==="

# Test 1/4: Rule trigger — expect ruleshield-rule
echo "  [1/4] Rule trigger: hello"
RESP="$(curl -sf "$PROXY_URL/v1/chat/completions" \
  -H "Content-Type: application/json" -H "Authorization: Bearer sk-test" \
  -d '{"model":"'"$MODEL"'","messages":[{"role":"user","content":"hello"}]}')"
echo "$RESP" | "$PYTHON_BIN" -c "import sys,json; d=json.load(sys.stdin); assert d['model']=='ruleshield-rule', f'Expected rule hit, got {d[\"model\"]}'; print('    PASS')"

# Test 2/4: Rule trigger — expect ruleshield-rule
echo "  [2/4] Rule trigger: thanks"
RESP="$(curl -sf "$PROXY_URL/v1/chat/completions" \
  -H "Content-Type: application/json" -H "Authorization: Bearer sk-test" \
  -d '{"model":"'"$MODEL"'","messages":[{"role":"user","content":"thanks"}]}')"
echo "$RESP" | "$PYTHON_BIN" -c "import sys,json; d=json.load(sys.stdin); assert d['model']=='ruleshield-rule', f'Expected rule hit, got {d[\"model\"]}'; print('    PASS')"

# Test 3/4: Passthrough — expect choices in response
echo "  [3/4] Passthrough: Explain the difference between TCP and U..."
RESP="$(curl -sf "$PROXY_URL/v1/chat/completions" \
  -H "Content-Type: application/json" -H "Authorization: Bearer sk-test" \
  -d '{"model":"'"$MODEL"'","messages":[{"role":"user","content":"Explain the difference between TCP and UDP in networking"}]}')"
echo "$RESP" | "$PYTHON_BIN" -c "import sys,json; d=json.load(sys.stdin); assert 'choices' in d; print('    PASS')"

# Test 4/4: Passthrough — expect choices in response
echo "  [4/4] Passthrough: What are the main features of Python 3.1..."
RESP="$(curl -sf "$PROXY_URL/v1/chat/completions" \
  -H "Content-Type: application/json" -H "Authorization: Bearer sk-test" \
  -d '{"model":"'"$MODEL"'","messages":[{"role":"user","content":"What are the main features of Python 3.12?"}]}')"
echo "$RESP" | "$PYTHON_BIN" -c "import sys,json; d=json.load(sys.stdin); assert 'choices' in d; print('    PASS')"

echo "=== ALL PASSED: GPT-4o ==="
