"""Shared fixtures for auto-generated model tests."""
# Generated by scripts/generate_model_tests.py from models/registry.yaml
# DO NOT EDIT — regenerate with: python scripts/generate_model_tests.py

import asyncio
import json
import os
import pytest
from ruleshield.rules import RuleEngine
from ruleshield.router import SmartRouter


@pytest.fixture
def engine():
    """RuleEngine loaded with bundled default rules."""
    e = RuleEngine()
    asyncio.run(e.init())
    return e


@pytest.fixture
def free_router():
    """SmartRouter with free model enforcement enabled."""
    return SmartRouter(config={
        "free_model_enforcement": {
            "enabled": True,
            "allowed_models": [
            "nvidia/nemotron-3-super-120b-a12b:free",
            "minimax/minimax-m2.5:free"
            ],
            "default_model": "nvidia/nemotron-3-super-120b-a12b:free",
        }
    })


@pytest.fixture
def prompts():
    """Load test prompt fixtures."""
    fixture_path = os.path.join(
        os.path.dirname(__file__), "..", "..", "fixtures", "prompts.json"
    )
    with open(fixture_path) as f:
        return json.load(f)
