"""Auto-generated integration test for gpt-4o-mini"""
# Generated by scripts/generate_model_tests.py from models/registry.yaml
# DO NOT EDIT — regenerate with: python scripts/generate_model_tests.py

import pytest

MODEL_ID = "gpt-4o-mini"
MODEL_NAME = "GPT-4o Mini"
PROVIDER = "openai"
TIER = "cheap"
CONFIDENCE_THRESHOLD = 0.6


class TestModelRouting:
    """Verify routing and threshold behavior for GPT-4o Mini."""

    def test_confidence_threshold_applied(self, engine):
        """Engine should respect confidence threshold for this model."""
        from ruleshield.rules import _get_model_threshold
        threshold = _get_model_threshold(MODEL_ID)
        assert threshold == pytest.approx(CONFIDENCE_THRESHOLD, abs=0.01)


class TestModelRuleMatch:
    """Verify rule matching works correctly with this model."""

    def test_rule_trigger_hello(self, engine):
        """Rule should fire for: hello"""
        result = engine.match("hello", model=MODEL_ID)
        assert result is not None, "Expected rule match for \"hello\""
        assert result["rule_id"] != ""

    def test_rule_trigger_thanks(self, engine):
        """Rule should fire for: thanks"""
        result = engine.match("thanks", model=MODEL_ID)
        assert result is not None, "Expected rule match for \"thanks\""
        assert result["rule_id"] != ""

    def test_passthrough_0(self, engine):
        """No rule should match: Explain the difference between TCP and UDP in netw"""
        result = engine.match("Explain the difference between TCP and UDP in networking", model=MODEL_ID)
        assert result is None, "Expected no rule match for passthrough prompt"

    def test_passthrough_1(self, engine):
        """No rule should match: What are the main features of Python 3.12?"""
        result = engine.match("What are the main features of Python 3.12?", model=MODEL_ID)
        assert result is None, "Expected no rule match for passthrough prompt"

    def test_temporal_passthrough(self, engine):
        """Temporal queries should NOT match rules (always go to LLM)."""
        result = engine.match("What time is it in LA right now?", model=MODEL_ID)
        assert result is None, "Temporal query should not match any rule"
