"""Auto-generated integration test for arcee-ai/trinity-large-preview:free"""
# Generated by scripts/generate_model_tests.py from models/registry.yaml
# DO NOT EDIT — regenerate with: python scripts/generate_model_tests.py

import pytest

MODEL_ID = "arcee-ai/trinity-large-preview:free"
MODEL_NAME = "Arcee Trinity Large Preview"
PROVIDER = "openrouter"
TIER = "free"
CONFIDENCE_THRESHOLD = 0.75


class TestModelRouting:
    """Verify routing and threshold behavior for Arcee Trinity Large Preview."""

    def test_confidence_threshold_applied(self, engine):
        """Engine should respect confidence threshold for this model."""
        from ruleshield.rules import _get_model_threshold
        threshold = _get_model_threshold(MODEL_ID)
        assert threshold == pytest.approx(CONFIDENCE_THRESHOLD, abs=0.01)

    def test_free_enforcement_allows_model(self, free_router):
        """Router allowlist should accept this free model."""
        result = free_router.route(
            "hello", None, MODEL_ID,
            provider_url="https://openrouter.ai/api/v1",
        )
        # Final model should be free (same or another from allowlist)
        final_model = result["model"] if result["routed"] else MODEL_ID
        allowed = free_router._free_allowed_models
        assert final_model in allowed, f"Expected free model, got {final_model}"

    def test_free_enforcement_blocks_expensive(self, free_router):
        """Router should block expensive models and replace with free."""
        result = free_router.route(
            "hello", None, "gpt-5.3-codex",
            provider_url="https://openrouter.ai/api/v1",
        )
        assert result["routed"] is True


class TestModelRuleMatch:
    """Verify rule matching works correctly with this model."""

    def test_rule_trigger_hello(self, engine):
        """Rule should fire for: hello"""
        result = engine.match("hello", model=MODEL_ID)
        assert result is not None, "Expected rule match for \"hello\""
        assert result["rule_id"] != ""

    def test_rule_trigger_thanks(self, engine):
        """Rule should fire for: thanks"""
        result = engine.match("thanks", model=MODEL_ID)
        assert result is not None, "Expected rule match for \"thanks\""
        assert result["rule_id"] != ""

    def test_passthrough_0(self, engine):
        """No rule should match: Explain the difference between TCP and UDP in netw"""
        result = engine.match("Explain the difference between TCP and UDP in networking", model=MODEL_ID)
        assert result is None, "Expected no rule match for passthrough prompt"

    def test_passthrough_1(self, engine):
        """No rule should match: What are the main features of Python 3.12?"""
        result = engine.match("What are the main features of Python 3.12?", model=MODEL_ID)
        assert result is None, "Expected no rule match for passthrough prompt"

    def test_temporal_passthrough(self, engine):
        """Temporal queries should NOT match rules (always go to LLM)."""
        result = engine.match("What time is it in LA right now?", model=MODEL_ID)
        assert result is None, "Temporal query should not match any rule"
